### ISSUE TITLE
Inconsistency between zkSync Explorer and zkFlow transaction counts

### ISSUE THREAD

**Issue by rayaanr** [ByFishh/zk-flow#12]
In zkSync Explorer, it shows that there are 12 committed nonces. In zkFlow, it shows 15 transactions. Actually, in total, there are 15 txns in my address, including token approvals. However, I think zkSync Explorer removes token approvals from the count (I'm not sure). In this case, I think it would be better to either remove token approvals from zkFlow, or add an option to view them separately. This is just my opinion. If you agree, please look into this.

<img width="1102" alt="Xnip2023-05-30_12-28-37" src="https://github.com/ByFishh/zk-flow/assets/108685206/e2d55928-6fa0-4e92-aeca-998196905ad9">

**Comment by ByFishh** [comment]
Hey, in zkFlow it display the total count of transactions instead of nonce (that are display in explorer). Nonce is the number of transaction emited by the wallet.
For exemple if you receive some ETH from a random wallet. The transaction will count in transactions count but not in Committed nonce.

If you want to know what is nonce: https://medium.com/coinmonks/the-account-nonce-in-ethereum-explained-c087bd4a3c29

**Comment by rayaanr** [comment]
Oh thanks. Im a noob in this field. So thanks for the info.
